title: Hungnv950
subtitle: Make life simple
description: >- # this means to ignore newlines until "baseurl:"
  Make life simple

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: Home
      url: /
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: About
      url: /about
    # - text: Shop
    #   url : /shop
    - text: Contact
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit Author details (For multi authors check _data/authors.yml)
author_logo: profile.png
author: Hung Nguyen
author_bio: Hi, my name is Hung Nguyen
author_email: "hungnv950@gmail.com"
author_location: VietNam
author_website_url: "hungnv950.github.io"
typewrite-text: Make life simple

# Experiences
author_work_experiences:
            - company_name: Sotatek
              company_logo: sotatek.jpeg
              company_url: https://sotatek.com/
              designation: Project Manager, Leader Engineer
              description: Project Manager, Leader Engineer
              visibility: true
            - company_name: Sun*
              company_logo: sun_asterisk.png
              company_url: https://sun-asterisk.vn/
              designation: Ruby on Rails Developer
              description: Ruby on Rails Developer
              visibility: true

# Education
author_education_details:
              - college_logo: uet.png
                college_name: University of Engineering and technology (UET)
                college_url: https://uet.vnu.edu.vn/
                college_degree: IT Engineer
                description: Information Systom
                visibility: true

# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
twitter_username: hungnv950
github_username:  hungnv950
facebook_username: hungnv950
linkedin_username: hungnv950
instagram_username: langthang.108

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: hungnv950

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: 'f/moqyqqye'

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 20
per_page: 20
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category:  '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
